# Generated by Django 5.0.6 on 2024-11-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('cargo_persona', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
            ],
        ),
    ]
