# Generated by Django 5.0.3 on 2024-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_articulo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
