# Generated by Django 5.0.3 on 2024-11-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_articulo_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='prestado',
        ),
    ]
